updated UserData in attempt to enable ssh brute force attacks using script

diff --git a/infra.yaml b/infra.yaml
--- a/infra.yaml
+++ b/infra.yaml
@@ -166,43 +166,49 @@ Resources:
         - Key: Name
           Value: RedTeamInstance
       UserData:
-        Fn::Base64: !Sub 
-        - |
-          #!/bin/bash
-          set -xe
+        Fn::Base64:
+          Fn::Sub:
+            - |
+              #!/bin/bash
+              set -xe
 
-          # Update system and install tools
-          yum update -y
-          yum install -y git nmap nc python3
+              # Avoid failing on update timeout
+              yum update -y || echo "yum update failed, continuing anyway"
 
-          # Install pip + paramiko
-          python3 -m ensurepip --upgrade
-          pip3 install --upgrade pip
-          pip3 install paramiko
+              # Proceed with installation
+              yum install -y git nmap nc python3 || echo "yum install failed"
 
-          # Clone crowbar
-          git clone https://github.com/galkan/crowbar /home/ec2-user/crowbar
-          chmod +x /home/ec2-user/crowbar/crowbar.py
+              # Install pip + paramiko
+              python3 -m ensurepip --upgrade
+              /usr/local/bin/pip3 install --upgrade pip
+              /usr/local/bin/pip3 install paramiko
 
-          # Create dummy compromised keys
-          mkdir -p /home/ec2-user/compromised_keys
-          echo "FAKE_KEY" > /home/ec2-user/compromised_keys/fakekey.pem
-          for i in {1..20}; do
-            cp /home/ec2-user/compromised_keys/fakekey.pem /home/ec2-user/compromised_keys/compromised${i}.pem
-          done
+              # Clone crowbar
+              git clone https://github.com/galkan/crowbar /home/ec2-user/crowbar
+              chmod +x /home/ec2-user/crowbar/crowbar.py
 
-          # Inject IPs into sourced file
-          echo 'BASIC_LINUX_TARGET="${LinuxTargetIP}"' > /home/ec2-user/localIps.sh
-          echo "RED_TEAM_IP=\"$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)\"" >> /home/ec2-user/localIps.sh
+              # Create dummy compromised keys
+              mkdir -p /home/ec2-user/compromised_keys
+              echo "FAKE_KEY" > /home/ec2-user/compromised_keys/fakekey.pem
+              for i in {1..20}; do
+                cp /home/ec2-user/compromised_keys/fakekey.pem /home/ec2-user/compromised_keys/compromised$i.pem
+              done
 
-          # Download the full GuardDuty tester script
-          curl -L -o /home/ec2-user/guardduty_tester.sh \
-            https://raw.githubusercontent.com/awslabs/amazon-guardduty-tester/main/guardduty_tester.sh
-          chmod +x /home/ec2-user/guardduty_tester.sh
+              # Inject IPs into sourced file
+              echo 'BASIC_LINUX_TARGET="${LinuxTargetIP}"' > /home/ec2-user/localIps.sh
+              echo "RED_TEAM_IP=\"$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)\"" >> /home/ec2-user/localIps.sh
 
-          # Fix ownership
-          chown -R ec2-user:ec2-user /home/ec2-user
-        - { LinuxTargetIP: !GetAtt LinuxTargetInstance.PrivateIp }
+              # Download the full GuardDuty tester script
+              curl -L -o /home/ec2-user/guardduty_tester.sh \
+                https://raw.githubusercontent.com/awslabs/amazon-guardduty-tester/9ed7b5f6057bda5cbf7ac3608555fe36e7a7c5fe/guardduty_tester.sh
+              chmod +x /home/ec2-user/guardduty_tester.sh
+
+              # Fix ownership
+              chown -R ec2-user:ec2-user /home/ec2-user
+            - LinuxTargetIP: 
+                Fn::GetAtt: 
+                  - LinuxTargetInstance
+                  - PrivateIp
 
   LinuxTargetInstance:
     Type: AWS::EC2::Instance
